name: main branch sync

on:
  push:
    branches:
      - 'master'


jobs:
  branch_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update branch
        run: |
          git fetch origin main
          git push https://${{ github.token }}@github.com/${{ github.repository }} HEAD:main
          
